### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by ryuki-hmst** [ryuki-hmst/chat-space#9]
# IPアドレス
54.150.141.225

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

### [修正箇所]
**①テキストや画像を送信すると、それまでに送信した内容がもう一度送信されてしまうので、送信されないようにしましょう
②グループ編集画面と新規グループ作成画面で、ユーザーの削除ボタンが押せるようにしましょう**

修正が完了次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by ryuki-hmst** [comment]
二点とも修正しました。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
※今後実装に関する質問がありましたら、メンターに確認をお願いします！
